### ISSUE TITLE
Backend - Create organizations schema

### ISSUE THREAD

**Issue by navidboloorian** [TritonSE/TSE-Moneta#21]
- Create organizations schema in the models folder with the following fields
- Name (string, required, index true)
- Email (string, required)
- Password (string, required)
- Approved Users (array of objectIds, reference users collection, not required)
- Status (string, required, default: "pending")
- Timestamps true

[Getting started with references](https://harrisonstandeffer.com/simulating-sql-joins-with-mongoose/)

**Comment by ainesh01** [comment]
@navidboloorian does password need to be hashed here, similarly to users?
